export const FETCH_POSTS ='FETCH_POSTS';
export const NEW_POST ='NEW_POST';
export const FETCH_FILTER = 'FETCH_FILTER';
export const ADD_A_FILTER = 'ADD_A_FILTER';
export const SUBMIT_FILTERS = 'SUBMIT_FILTERS';
export const CHANGE_SELECTIONS = 'CHANGE_SELECTIONS';